-- =============================================
-- IMPORTAÇÃO DE DADOS - COMPRAS.PDF
-- Execute no SQL Editor do Supabase
-- =============================================

-- 0. Remover UNIQUE em numero_processo (um RC pode ter múltiplos centros de custo)
ALTER TABLE compras_processos
  DROP CONSTRAINT IF EXISTS compras_processos_numero_processo_key;

-- 1. Atualizar CHECK constraint de status para incluir novos valores
ALTER TABLE compras_processos
  DROP CONSTRAINT IF EXISTS compras_processos_status_check;

ALTER TABLE compras_processos
  ADD CONSTRAINT compras_processos_status_check
  CHECK (status IN (
    'EM COTAÇÃO',
    'EM APROVAÇÃO',
    'PCBS EM APROVAÇÃO',
    'PENDENTE APROVAÇÃO',
    'COMPARATIVO',
    'ABRIR REQUISIÇÃO',
    'CONVERTER REQUISIÇÃO',
    'PROCESSO COM RJ',
    'LIBERADO',
    'PEDIDO EMITIDO',
    'RECEBIDO',
    'CANCELADO'
  ));

-- 2. Limpar dados inseridos anteriormente (para evitar duplicatas ao re-executar)
TRUNCATE TABLE compras_cotacoes CASCADE;
TRUNCATE TABLE compras_processos CASCADE;
TRUNCATE TABLE compras_fornecedores CASCADE;

-- 3. Inserir fornecedores da planilha
INSERT INTO compras_fornecedores (razao_social, ativo) VALUES
  ('ANTONIO NERES DA SILVA', true),
  ('VERBOONEN E VERBOONEN CONSULTORIA LTDA', true),
  ('SOLIDES TECNOLOGIA S/A', true),
  ('IDIOMAS VALE CENTER LTDA', true),
  ('TRANSDIAS TRANSPORTES LTDA', true),
  ('TREINAMENTOS DO VALLE - SERVICOS DE PERICIA EM SEGURANCA DO TRABALHO LTDA', true),
  ('FRANCISCO EDNALDO DOS SANTOS', true),
  ('CAFE COM PAO PADARIA LTDA', true),
  ('OBELISCO COMERCIO E SERVICOS LTDA', true),
  ('V CORDEIRO FEITOZA DA SILVA', true),
  ('ACERT INFORMATICA COMERCIO E SERVICOS LTDA', true),
  ('WILLIAN DAMASCENO SOUZA 05786790517', true),
  ('NILTON MANOEL DE BRITO NETO', true),
  ('TRANSFORT RENTAL E TRANSPORTES LTDA', true),
  ('TEC UNIFORMES LTDA', true),
  ('TEREX BETIM EQUIPAMENTOS LTDA', true),
  ('WORK SERVICE SISTEMAS E SERVICOS DE APOIO ADMINIST', true),
  ('BRFIBRA TELECOMUNICACOES', true),
  ('FLUILAB, IMPORTACAO E COMERCIO LTDA', true),
  ('EMBRATOP - LOCACAO', true),
  ('REI DAS TECNOLOGIAS', true),
  ('JACI ANGELICA DO NASCIMENTO', true),
  ('FARDADEZ FARDAMENTOS', true),
  ('STRATEGY SEGURANCA', true),
  ('ZEUS DO BRASIL LTDA', true),
  ('ALEX SANDRO PIRES', true),
  ('TESTSAFE ENSAIOS E INSPECOES', true),
  ('QUALISERV LTDA', true),
  ('NP UNIFORMES LTDA', true),
  ('MARCOS NASCIMENTO', true),
  ('INSTITUTO ABRATE DO BRASIL', true),
  ('MARCUS VINICIUS DA SILVA', true),
  ('KALI COMERCIAL TECNOLOGIA', true),
  ('GARDEIS COMERCIO E SERVICOS', true),
  ('OURO VERDE LOCACAO E SERVICOS SA', true)
ON CONFLICT DO NOTHING;

-- 4. Inserir os 57 processos de compra
INSERT INTO compras_processos (
  numero_processo, numero_requisicao, numero_pedido,
  status, centro_custo, projeto,
  produto_nome, categoria, unidade,
  fornecedor_escolhido_nome, responsavel_compra, solicitante,
  data_pedido, quantidade, preco_escolhido, observacoes
) VALUES
-- 1
('RC000964','PCBS-47081',NULL,'LIBERADO','CENTRO OPERACIONAL','CENTRO OPERACIONAL','CONSULTORIA INTERNA','CONSULTORIA','MÊS','ANTONIO NERES DA SILVA','JOSE LUCENA','RODRIGO.FARIA','2026-03-11',3,75000,NULL),
-- 2
(NULL,'PCBS-46215',NULL,'LIBERADO','CENTRO OPERACIONAL','CENTRO OPERACIONAL','CONSULTORIA INTERNA','CONSULTORIA','MÊS','VERBOONEN E VERBOONEN CONSULTORIA LTDA','JOSE LUCENA','RODRIGO.FARIA','2026-01-01',3,93000,NULL),
-- 3
('RC000961','PCBS-46869',NULL,'LIBERADO','CENTRO OPERACIONAL','CENTRO OPERACIONAL','SISTEMA DE PONTO - SOLIDES','RH','MÊS','SOLIDES TECNOLOGIA S/A','JOSE LUCENA','RODRIGO.FARIA','2026-03-03',12,132021.82,NULL),
-- 4
('RC000956','PCBS-47051',NULL,'LIBERADO','CENTRO OPERACIONAL','CENTRO OPERACIONAL','CURSO INGLES','TREINAMENTOS','MÊS','IDIOMAS VALE CENTER LTDA','TIAGO SILVA','RODRIGO.FARIA','2026-03-11',10,78400,NULL),
-- 5
('RC000955','PCBS-46831',NULL,'LIBERADO','CENTRO OPERACIONAL','CENTRO OPERACIONAL','TRANSPORTE DE PASSAGEIRO','VEICULOS','MÊS','TRANSDIAS TRANSPORTES LTDA','JOSE LUCENA','RODRIGO.FARIA','2026-02-25',6,112800,NULL),
-- 6
(NULL,'PCBS-46942',NULL,'LIBERADO','CENTRO OPERACIONAL','CENTRO OPERACIONAL','TREINAMENTOS','SEGURANÇA','MÊS','TREINAMENTOS DO VALLE - SERVICOS DE PERICIA EM SEGURANCA DO TRABALHO LTDA','JOSE LUCENA','RODRIGO.FARIA','2026-03-03',1,5000,NULL),
-- 7
(NULL,'PCBS-46934',NULL,'LIBERADO','CENTRO OPERACIONAL','CENTRO OPERACIONAL','CARPITARIA E SERRALHERIA','CARPITARIA E SERRALHERIA','SV','FRANCISCO EDNALDO DOS SANTOS','TIAGO SILVA','RODRIGO.FARIA','2026-03-09',1,4992,NULL),
-- 8
(NULL,'PCBS-46928',NULL,'LIBERADO','CENTRO OPERACIONAL','CENTRO OPERACIONAL','COFFE BREAK','CANTINA CANTEIRO','UND','CAFE COM PAO PADARIA LTDA','TIAGO SILVA','RODRIGO.FARIA','2026-03-12',1,461.49,NULL),
-- 9
(NULL,'PCBS-46927',NULL,'LIBERADO','55221BS','O&M COMISIONADO MANTIQUEIRA','BOLSA NOTEBOOK','ESCRITORIO','UND','OBELISCO COMERCIO E SERVICOS LTDA','TIAGO SILVA','RODRIGO.FARIA','2026-03-11',2,680,NULL),
-- 10
(NULL,'PCBS-46926',NULL,'LIBERADO','CENTRO OPERACIONAL','CENTRO OPERACIONAL','DEDETIZAÇÃO','DEDETIZAÇÃO, LIMPEZAS','SV','V CORDEIRO FEITOZA DA SILVA','TIAGO SILVA','RODRIGO.FARIA','2026-03-10',1,2160,NULL),
-- 11
(NULL,'PCBS-46925',NULL,'LIBERADO','CENTRO OPERACIONAL','CENTRO OPERACIONAL','KIT MOUSE + TECLADO','INFORMATICA','UND','ACERT INFORMATICA COMERCIO E SERVICOS LTDA','TIAGO SILVA','RODRIGO.FARIA','2026-03-06',1,1747,NULL),
-- 12
(NULL,'PCBS-46921',NULL,'LIBERADO','CENTRO OPERACIONAL','CENTRO OPERACIONAL','ABASTECIMENTO AGUA','FRETES E CARRETOS','UND','WILLIAN DAMASCENO SOUZA 05786790517','TIAGO SILVA','RODRIGO.FARIA','2026-03-03',3,900,NULL),
-- 13
(NULL,'PCBS-46913',NULL,'LIBERADO','CENTRO OPERACIONAL','CENTRO OPERACIONAL','BATERIA','MANUT. MAQ. EQUIP.','UND','NILTON MANOEL DE BRITO NETO','TIAGO SILVA','RODRIGO.FARIA','2026-03-03',1,680,NULL),
-- 14
(NULL,'PCBS-46886',NULL,'LIBERADO','CENTRO OPERACIONAL','CENTRO OPERACIONAL','DEVOLUÇÃO NOTEBOOK','FRETES E CARRETOS','SV','TRANSFORT RENTAL E TRANSPORTES LTDA','JOSE LUCENA','RODRIGO.FARIA','2026-03-02',1,1600,NULL),
-- 15
(NULL,'PCBS-46611',NULL,'LIBERADO','CENTRO OPERACIONAL','CENTRO OPERACIONAL','FARDAMENTO ADMINISTRATIVO','UNIFORMES','UND','TEC UNIFORMES LTDA','JOSE LUCENA','RODRIGO.FARIA','2026-02-13',29,4057.50,NULL),
-- 16
(NULL,'PCBS-46608',NULL,'LIBERADO','CENTRO OPERACIONAL','CENTRO OPERACIONAL','FARDAMENTO ADMINISTRATIVO','UNIFORMES','UND','TEC UNIFORMES LTDA','JOSE LUCENA','RODRIGO.FARIA','2026-02-13',29,4057.50,NULL),
-- 17
('RC000865','PCBS-46231',NULL,'PCBS EM APROVAÇÃO','55253BS','O&M ELETROBRAS ELETROSUL','MATERIAL LINHA VIVA','LINHA VIVA','UND','TEREX BETIM EQUIPAMENTOS LTDA','JOSE LUCENA','RODRIGO.FARIA','2026-03-14',1,591973.80,NULL),
-- 18
('RC000918',NULL,NULL,'PROCESSO COM RJ','CENTRO OPERACIONAL','CENTRO OPERACIONAL','VIGILANCIA E PORTARIA','SEGURANÇA','MÊS','WORK SERVICE SISTEMAS E SERVICOS DE APOIO ADMINIST','JOSE LUCENA','RODRIGO.FARIA','2025-11-21',12,376800,'PROCESSO ESTAR COM RJ'),
-- 19
(NULL,NULL,NULL,'EM COTAÇÃO','55250BS','O&M SERENA - DELTA MARANHÃO','TERMOVISOR','ATIVO FIXO','UND',NULL,'JOSE LUCENA','RODRIGO.FARIA','2026-03-16',1,NULL,'PROCESSO PARADO'),
-- 20
(NULL,'PCBS-40637',NULL,'LIBERADO','CENTRO OPERACIONAL','CENTRO OPERACIONAL','LINK DE COMUNICAÇÃO','INFORMATICA','MÊS','BRFIBRA TELECOMUNICACOES','JOSE LUCENA','RODRIGO.FARIA','2026-03-11',12,207600,NULL),
-- 21
('RC000934','PCBS-46366',NULL,'LIBERADO','55252BS','O&M ELETROBRAS CHESF','MATERIAL LINHA VIVA','LINHA VIVA','UND','TEREX BETIM EQUIPAMENTOS LTDA','JOSE LUCENA','RODRIGO.FARIA','2026-03-16',1,44214.08,NULL),
-- 22
('RC000941','PCBS-46617',NULL,'LIBERADO','55221BS','O&M COMISIONADO MANTIQUEIRA','ANALISE DE OLEO','MANUT. MAQ. EQUIP.','SV','FLUILAB, IMPORTACAO E COMERCIO LTDA','JOSE LUCENA','GILSOMAR.COUTO','2026-03-09',1,50318,NULL),
-- 23
('RC000954',NULL,NULL,'COMPARATIVO','55221BS','O&M COMISIONADO MANTIQUEIRA','DRONE','ATIVO FIXO','UND','EMBRATOP - LOCACAO','JOSE LUCENA','RODRIGO.FARIA','2026-03-16',3,352735.30,'COMPARATIVO ASSINATURA'),
-- 24
('RC000942','PCBS-46680',NULL,'LIBERADO','CENTRO OPERACIONAL','CENTRO OPERACIONAL','STARLINK','INFORMATICA','MÊS','REI DAS TECNOLOGIAS','TIAGO SILVA','GILSOMAR.COUTO','2026-01-23',12,19500,NULL),
-- 25
(NULL,'PCBS-46819',NULL,'LIBERADO','CENTRO OPERACIONAL','CENTRO OPERACIONAL','ANALISE DE AGUA POTAVEL','ANALISES LABORATORIAIS','SV','JACI ANGELICA DO NASCIMENTO','TIAGO SILVA','GILSOMAR.COUTO','2026-02-24',2,400,NULL),
-- 26
(NULL,NULL,NULL,'EM COTAÇÃO','CENTRO OPERACIONAL','CENTRO OPERACIONAL','CADEIRA ESCRITORIO','ESCRITORIO','UND',NULL,'JOSE LUCENA','RODRIGO.FARIA','2026-03-05',3,NULL,NULL),
-- 27
('RC000957','PCBS-46813',NULL,'LIBERADO','55227BS','O&M SERTANEJA','FARDAMENTOS ANTI CHAMAS','EPI','UND','FARDADEZ FARDAMENTOS','JOSE LUCENA','STENIO.MARTINS','2026-02-19',38,9500,NULL),
-- 28
(NULL,NULL,NULL,'EM COTAÇÃO','55256BS','O&M VERDE TRANSMISSÃO','ELETRODOMESTICO','ESCRITORIO','UND',NULL,'JOSE LUCENA','GILSOMAR.COUTO','2026-02-12',1,NULL,'PROCESSO FEITO PELO PROJETO'),
-- 29
('RC000950','PCBS-46681',NULL,'LIBERADO','55220BS/001','JMM TRANSMISSORA DE ENERGIA','EPI / EPC','EPI','UND','STRATEGY SEGURANCA','JOSE LUCENA','STENIO.MARTINS','2026-02-11',1,19399.60,NULL),
-- 30
(NULL,NULL,NULL,'EM COTAÇÃO','55252BS','O&M ELETROBRAS CHESF','FRETE','FRETES E CARRETOS','SV','TRANSFORT RENTAL E TRANSPORTES LTDA','JOSE LUCENA','ANTONIO.NASCIMENTO','2026-02-04',1,NULL,'REGULARIZAR PROCESSO'),
-- 31
('RC000949','PCBS-46871',NULL,'LIBERADO','55220BS/001','JMM TRANSMISSORA DE ENERGIA','MATERIAL LINHA VIVA','LINHA VIVA','UND','TEREX BETIM EQUIPAMENTOS LTDA','JOSE LUCENA','STENIO.MARTINS','2026-02-11',1,22793.35,NULL),
-- 32
(NULL,NULL,NULL,'EM COTAÇÃO','CENTRO OPERACIONAL','CENTRO OPERACIONAL','TV','ESCRITORIO','UND',NULL,'TIAGO SILVA','RODRIGO.FARIA','2026-02-09',6,NULL,NULL),
-- 33
('RC000959','PCBS-47266',NULL,'PCBS EM APROVAÇÃO','55221BS','O&M COMISIONADO MANTIQUEIRA','FARDAMENTOS ANTI CHAMAS','EPI','UND','FARDADEZ FARDAMENTOS','JOSE LUCENA','GILSOMAR.COUTO','2026-02-23',45,11250,NULL),
-- 34
(NULL,NULL,NULL,'EM COTAÇÃO','CENTRO OPERACIONAL','CENTRO OPERACIONAL','SUPORTE ARTICULADO TV','ESCRITORIO','UND',NULL,'JOSE LUCENA','RODRIGO.FARIA','2026-02-25',16,NULL,NULL),
-- 35
('RC000963',NULL,NULL,'EM COTAÇÃO','55256BS','O&M VERDE TRANSMISSÃO','FERRAMENTAL','FERRAMENTAS','UND',NULL,'JOSE LUCENA','GILSOMAR.COUTO','2026-02-18',1,NULL,NULL),
-- 36
('RC000962',NULL,NULL,'EM COTAÇÃO','55256BS','O&M VERDE TRANSMISSÃO','EPI / EPC','EPI','UND',NULL,'JOSE LUCENA','GILSOMAR.COUTO','2026-02-18',1,NULL,NULL),
-- 37
('RC000971','PCBS-47160',NULL,'LIBERADO','CENTRO OPERACIONAL','CENTRO OPERACIONAL','BATERIA','MANUT. MAQ. EQUIP.','UND','NILTON MANOEL DE BRITO NETO','JOSE LUCENA','RODRIGO.FARIA','2026-03-02',10,19472,NULL),
-- 38
(NULL,NULL,NULL,'ABRIR REQUISIÇÃO','CENTRO OPERACIONAL','CENTRO OPERACIONAL','ALUGUEIS DE VEICULOS','VEICULOS','SV','OURO VERDE LOCACAO E SERVICOS SA','JOSE LUCENA','RODRIGO.FARIA','2026-03-16',1,NULL,NULL),
-- 39
('RC000973',NULL,NULL,'PENDENTE APROVAÇÃO','55253BS','O&M ELETROBRAS ELETROSUL','EPI / EPC','EPI','UND','ZEUS DO BRASIL LTDA','TIAGO SILVA','RODRIGO.FARIA','2026-03-17',1,8981.21,NULL),
-- 40
(NULL,'PCBS-47208',NULL,'PCBS EM APROVAÇÃO','55221BS','O&M COMISIONADO MANTIQUEIRA','CONTAINER','ALUGUEL MAQUINAS E EQUIP. - PJ','SV','ALEX SANDRO PIRES','TIAGO SILVA','GILSOMAR.COUTO','2026-03-18',1,1000,NULL),
-- 41
(NULL,'PCBS-47275',NULL,'PENDENTE APROVAÇÃO','55220BS/001','JMM TRANSMISSORA DE ENERGIA','AFERIÇÃO DE EQUIP./FERRAMENTAS','MANUT. MAQ. EQUIP.','SV','TESTSAFE ENSAIOS E INSPECOES','JOSE LUCENA','STENIO.MARTINS','2026-03-18',1,2550,NULL),
-- 42
(NULL,'PCBS-47277',NULL,'LIBERADO','55220BS/001','JMM TRANSMISSORA DE ENERGIA','AFERIÇÃO DE EQUIP./FERRAMENTAS','MANUT. MAQ. EQUIP.','SV','QUALISERV LTDA','JOSE LUCENA','STENIO.MARTINS','2026-03-18',1,2600,NULL),
-- 43.1
('RC000974',NULL,NULL,'COMPARATIVO','55240BS','PAMPA','FARDAMENTOS ANTI CHAMAS','EPI','UND','NP UNIFORMES LTDA','JOSE LUCENA','JOSE.AGUIRRE','2026-03-19',50,11845,'PROCESSO PARADO'),
-- 43.2
('RC000974',NULL,NULL,'COMPARATIVO','55245BS','O&M VINEYARDS','FARDAMENTOS ANTI CHAMAS','EPI','UND','NP UNIFORMES LTDA','JOSE LUCENA','JOSE.AGUIRRE','2026-03-19',50,11845,'PROCESSO PARADO'),
-- 43.3
('RC000974',NULL,NULL,'COMPARATIVO','55234BS','CHIMARRÃO','FARDAMENTOS ANTI CHAMAS','EPI','UND','NP UNIFORMES LTDA','JOSE LUCENA','JOSE.AGUIRRE','2026-03-19',70,16583,'PROCESSO PARADO'),
-- 44
(NULL,'PCBS-46933',NULL,'LIBERADO','CENTRO OPERACIONAL','CENTRO OPERACIONAL','CARPITARIA E SERRALHERIA','CARPITARIA E SERRALHERIA','SV','MARCOS NASCIMENTO','TIAGO SILVA','GILSOMAR.COUTO','2026-03-03',1,1800,NULL),
-- 45
(NULL,'PCBS-47265',NULL,'LIBERADO','CENTRO OPERACIONAL','CENTRO OPERACIONAL','TREINAMENTOS','SEGURANÇA','MÊS','INSTITUTO ABRATE DO BRASIL','JOSE LUCENA','GILSOMAR.COUTO','2026-03-24',1,7607.50,NULL),
-- 46
(NULL,NULL,NULL,'EM COTAÇÃO','CENTRO OPERACIONAL','CENTRO OPERACIONAL','MANUTENÇÃO COT','MANUT. MAQ. EQUIP.','SV',NULL,'JOSE LUCENA','GILSOMAR.COUTO','2026-03-23',1,NULL,NULL),
-- 47
(NULL,NULL,NULL,'EM COTAÇÃO','CENTRO OPERACIONAL','CENTRO OPERACIONAL','EPI / EPC','EPI','UND',NULL,'TIAGO SILVA','GILSOMAR.COUTO','2026-03-23',1,NULL,NULL),
-- 48
(NULL,NULL,NULL,'EM COTAÇÃO','CENTRO OPERACIONAL','CENTRO OPERACIONAL','EPI / EPC','EPI','UND',NULL,'TIAGO SILVA','GILSOMAR.COUTO','2026-03-23',1,NULL,NULL),
-- 49
(NULL,'PCBS-47259',NULL,'LIBERADO','CENTRO OPERACIONAL','CENTRO OPERACIONAL','PAPEL DE PAREDE SALA LIDAR','ESCRITORIO','SV','MARCUS VINICIUS DA SILVA','TIAGO SILVA','GILSOMAR.COUTO','2026-03-23',1,818.80,NULL),
-- 50
(NULL,'PCBS-47294',NULL,'PENDENTE APROVAÇÃO','CENTRO OPERACIONAL','CENTRO OPERACIONAL','MESA LIDAR','ESCRITORIO','UND','FRANCISCO EDNALDO DOS SANTOS','TIAGO SILVA','GILSOMAR.COUTO','2026-03-23',1,2750,NULL),
-- 51
(NULL,NULL,NULL,'EM COTAÇÃO','CENTRO OPERACIONAL','CENTRO OPERACIONAL','MESA REFEITORIO','CANTINA CANTEIRO','UND',NULL,'TIAGO SILVA','GILSOMAR.COUTO','2026-03-23',1,NULL,NULL),
-- 52
(NULL,'PCBS-47302',NULL,'LIBERADO','55220BS/001','JMM TRANSMISSORA DE ENERGIA','AFERIÇÃO DE EQUIP./FERRAMENTAS','MANUT. MAQ. EQUIP.','SV','KALI COMERCIAL TECNOLOGIA','JOSE LUCENA','STENIO.MARTINS','2026-03-24',1,1406.46,NULL),
-- 53
('RC000980',NULL,NULL,'CONVERTER REQUISIÇÃO','55252BS','O&M ELETROBRAS CHESF','FRETE','FRETES E CARRETOS','SV','TRANSFORT RENTAL E TRANSPORTES LTDA','JOSE LUCENA','ANTONIO.NASCIMENTO','2026-03-25',1,9800,NULL),
-- 54
(NULL,NULL,NULL,'EM COTAÇÃO','CENTRO OPERACIONAL','CENTRO OPERACIONAL','EPI / EPC','EPI','UND','GARDEIS COMERCIO E SERVICOS','TIAGO SILVA','GILSOMAR.COUTO','2026-03-20',1,NULL,NULL),
-- 55
(NULL,NULL,NULL,'EM COTAÇÃO','CENTRO OPERACIONAL','CENTRO OPERACIONAL','ADESIVO SEGURANÇA','GRAFICA','UND',NULL,'TIAGO SILVA','GILSOMAR.COUTO','2026-03-20',1,NULL,NULL),
-- 56
(NULL,NULL,NULL,'PENDENTE APROVAÇÃO','CENTRO OPERACIONAL','CENTRO OPERACIONAL','FARDAMENTOS ANTI CHAMAS','EPI','UND','FARDADEZ FARDAMENTOS','TIAGO SILVA','GILSOMAR.COUTO','2026-03-20',25,6250,NULL),
-- 57
(NULL,'PCBS-47366',NULL,'PENDENTE APROVAÇÃO','CENTRO OPERACIONAL','CENTRO OPERACIONAL','CONSULTORIA INTERNA','CONSULTORIA','MÊS','VERBOONEN E VERBOONEN CONSULTORIA LTDA','TIAGO SILVA','GILSOMAR.COUTO','2026-03-27',1,739.53,'3 - ENVIAR PROTOCOLO - 03/04');
